[package]
name = "on1giri_mass_client"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
reqwest = "0.12.4"
serde = {version = "1.0.199", features = ["derive", "std"]}
clap = { version = "4.5.4", features = ["derive"] }
